spring:
  profiles:
    active: dev
server:
  port: 8080
  servlet:
    context-path: /demo
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  #分页查询配置
  configuration-properties:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true