spring:
  profiles:
    active: prod
server:
  port: 8080
  servlet:
    context-path: / # todo 填入根路径
mybatis:
  config-location: classpath:mybatis-config.xml
  mapper-locations: classpath:/mapper/*.xml
  #分页查询配置
  configuration-properties:
    offsetAsPageNum: true
    rowBoundsWithCount: true
    reasonable: true